# numpy Study Notebook

# MAS DSE200

### Data

Download the `wine_data.csv` and `wine_modified.csv` data from Canvas and place the file in the same folder as this jupyter notebook.

In [1]:
import numpy as np

raw_data = np.genfromtxt('./wine_data.csv', delimiter=',')[1:]

**Question 1**: Write code to find out how many unique classes are there in the dataset.

In [2]:
## SOLUTION 1
np.unique(raw_data[:, -1])

array([1., 2., 3.])

**Question 2**: Calculate the row-wise sum of the data.

In [3]:
## SOLUTION 2
raw_data.sum(axis=1)

array([ 671.31    ,  614.91    , 1461.      ,  428.88    , 1671.6     ,
        570.3     ,  869.35    ,  666.42    ,  625.29    ,  527.67    ,
       1142.64    , 1292.52    ,  878.19    ,  631.12    ,  643.34    ,
        519.77    ,  659.51    ,  505.84    , 1702.52    ,  720.6     ,
       1302.79    ,  589.55    ,  630.72    ,  608.74    , 1445.95    ,
       1437.46    ,  611.059999, 1044.5     ,  966.36    , 1355.12    ,
        827.59    , 1197.46    , 1616.23    ,  525.59    ,  927.08    ,
        832.4     , 1248.08    ,  597.72    ,  700.57    ,  809.24    ,
        524.49    ,  656.85    ,  458.7     ,  762.32    , 1413.44    ,
        560.86    ,  827.85    ,  547.32    ,  723.56    ,  761.33    ,
       1139.88    ,  413.33    ,  601.6     , 1428.11    , 1469.78    ,
        697.57    ,  799.59    ,  714.3     ,  543.88    ,  498.54    ,
       1021.236   , 1039.27    ,  747.92    ,  841.02    ,  673.33    ,
        507.9     ,  915.92    , 1677.79    ,  921.95    , 1293.

**Question 3**: Calculate the column-wise mean of the data.

In [4]:
## SOLUTION 3
raw_data.mean(axis=0)

array([1.29517000e+01, 2.36250000e+00, 2.32670000e+00, 1.93720000e+01,
       9.80500000e+01, 2.25280000e+00, 1.98770000e+00, 3.68700000e-01,
       1.59900000e+00, 4.99539999e+00, 9.73760000e-01, 2.60500000e+00,
       7.17770000e+02, 1.94000000e+00])

**Question 4**: Calculate the class-wise mean and standard deviation of the each column.

In [5]:
## SOLUTION 4
print("Class 1: ")
print("\tMean: ", raw_data[raw_data[:, -1] == 1].mean(axis=0))
print("\tSTD: ", raw_data[raw_data[:, -1] == 1].std(axis=0))

print("\nClass 2: ")
print("\tMean: ", raw_data[raw_data[:, -1] == 2].mean(axis=0))
print("\tSTD: ", raw_data[raw_data[:, -1] == 2].std(axis=0))

print("\nClass 3: ")
print("\tMean: ", raw_data[raw_data[:, -1] == 3].mean(axis=0))
print("\tSTD: ", raw_data[raw_data[:, -1] == 3].std(axis=0))

Class 1: 
	Mean:  [1.37835484e+01 1.99774194e+00 2.43225806e+00 1.69645161e+01
 1.05967742e+02 2.87806452e+00 3.01935484e+00 2.90000000e-01
 2.00193548e+00 5.72774194e+00 1.06290323e+00 3.17129032e+00
 1.12425806e+03 1.00000000e+00]
	STD:  [4.83458964e-01 6.73032184e-01 2.43730545e-01 3.22085426e+00
 1.03065400e+01 3.07523084e-01 3.90036685e-01 7.02529990e-02
 4.26224379e-01 1.19693347e+00 1.04517125e-01 3.11994023e-01
 2.33113010e+02 0.00000000e+00]

Class 2: 
	Mean:  [1.22415909e+01 2.10977273e+00 2.18863636e+00 1.97909091e+01
 9.16136364e+01 2.15227273e+00 1.93113636e+00 3.81136364e-01
 1.55863636e+00 2.99909091e+00 1.07331818e+00 2.72613636e+00
 4.85681818e+02 2.00000000e+00]
	STD:  [4.80562848e-01 1.16372929e+00 2.97684938e-01 2.99369171e+00
 1.29828837e+01 4.73112824e-01 5.66441106e-01 1.23052389e-01
 6.10962694e-01 9.87360619e-01 2.23113890e-01 5.19589943e-01
 1.30644168e+02 0.00000000e+00]

Class 3: 
	Mean:  [1.31700000e+01 3.25960000e+00 2.43880000e+00 2.16200000e+01
 9.956000

Use `wine_modified.csv` for the following questions.

In [6]:
raw_data = np.genfromtxt('./wine_modified.csv', delimiter=',')[1:]

columns = open('./wine_modified.csv', 'r').readline().strip().split(',')

**Question 5**: Remove the rows with missing labels (’class’) and rows with more than 7 missing features. Report the remaining number of rows.

In [7]:
## SOLUTION 5

# remove the rows with more than 7 missing features
raw_data = raw_data[np.isnan(raw_data).sum(axis=1)<=7]

# remove the rows with missing labels
raw_data = raw_data[~np.isnan(raw_data[:, columns.index('class')])]

# get the number of rows
raw_data.shape[0]

154

**Question 6**: Remove features with >50% of missing values. For other features with missing values fill them with the mean of the corresponding features. Report the removed features (if any) and standard deviation of features with missing values after filling.

In [8]:
## SOLUTION 6

# get columns with > 50% missing values
remove_columns = np.where(np.isnan(raw_data).sum(axis=0) > (raw_data.shape[0] / 2))[0]
print("Removed columns: ", remove_columns)
print("Removed features: ", [columns[i] for i in remove_columns])

# bookkeeping
for column in remove_columns:
    del columns[column]

# remove those columns
raw_data = np.delete(raw_data, remove_columns, axis=1)

# get column with missing values
null_columns = np.where(np.isnan(raw_data).sum(axis=0) > 0)[0]

# Obtain mean of columns as you need, nanmean is just convenient.
col_mean = np.nanmean(raw_data, axis=0)

# Find indices that you need to replace
inds = np.where(np.isnan(raw_data))

# Place column means in the indices. Align the arrays using take
raw_data[inds] = np.take(col_mean, inds[1])

for i in null_columns:
    print("Standard deviation for feature (", columns[i], "): ", raw_data[:, i].std(axis=0))

Removed columns:  [3]
Removed features:  ['Ash']
Standard deviation for feature ( Magnesium ):  14.393416666995842
Standard deviation for feature ( Flavanoids ):  0.8707323233936536


**Question 7**: Detect and remove rows with any outliers/incorrect values in features ’alcohol’ and ’proline’ (if any). Clearly state the basis of your removal in comments.

In [9]:
## SOLUTION 7

# get feature indices
features = np.array([columns.index(feat_name) for feat_name in ['Alcohol', 'Proline']])

# get mean and std for columns
mu, sigma = np.mean(raw_data[:, features], axis=0), np.std(raw_data[:, features], axis=0, ddof=1)

# remove rows with outliers
raw_data = raw_data[np.all(np.abs((raw_data[:, features] - mu) / sigma) < 1, axis=1)].shape